use crate::models::task::ScanMode;

/// Domain candidate generated by the list generator
#[derive(Debug, Clone)]
pub struct DomainCandidate {
    pub domain: String,
    pub tld: String,
    pub index: i64,
}

/// Streaming domain list generator
/// Generates domain candidates based on scan mode, yielding batches
pub struct ListGenerator {
    mode: ScanMode,
    tld: String,
    current_index: i64,
    total_count: i64,
    batch_size: usize,
    // For regex/wildcard: pre-generated list
    candidates: Vec<String>,
}

impl ListGenerator {
    pub fn new(mode: ScanMode, tld: String) -> Self {
        let candidates = Self::generate_candidates(&mode);
        let total_count = candidates.len() as i64;
        Self {
            mode,
            tld,
            current_index: 0,
            total_count,
            batch_size: 5000,
            candidates,
        }
    }

    pub fn with_batch_size(mut self, batch_size: usize) -> Self {
        self.batch_size = batch_size;
        self
    }

    /// Resume from a specific index (for checkpoint resume)
    pub fn with_start_index(mut self, index: i64) -> Self {
        self.current_index = index;
        self
    }

    /// Get the total number of candidates
    pub fn total_count(&self) -> i64 {
        self.total_count
    }

    /// Get the current position
    pub fn current_index(&self) -> i64 {
        self.current_index
    }

    /// Check if there are more candidates
    pub fn has_more(&self) -> bool {
        self.current_index < self.total_count
    }

    /// Get the next batch of domain candidates
    pub fn next_batch(&mut self) -> Vec<DomainCandidate> {
        let end = std::cmp::min(self.current_index + self.batch_size as i64, self.total_count);
        let batch: Vec<DomainCandidate> = (self.current_index..end)
            .filter_map(|i| {
                self.candidates.get(i as usize).map(|prefix| DomainCandidate {
                    domain: format!("{}{}", prefix, self.tld),
                    tld: self.tld.clone(),
                    index: i,
                })
            })
            .collect();
        self.current_index = end;
        batch
    }

    /// Generate candidate prefixes based on scan mode
    fn generate_candidates(mode: &ScanMode) -> Vec<String> {
        match mode {
            ScanMode::Regex { pattern } => Self::generate_from_regex(pattern),
            ScanMode::Wildcard { pattern } => Self::generate_from_wildcard(pattern),
            ScanMode::Llm { prompt, .. } => {
                // For LLM mode, the prompt generates candidates that are stored as domains
                // In practice, these would come from the LLM API response
                // For now, we parse the prompt for test keywords
                prompt.split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect()
            }
            ScanMode::Manual { domains } => {
                // For manual mode, domains are provided directly
                domains.clone()
            }
        }
    }

    /// Generate domain prefixes from a regex pattern
    /// Supports limited patterns: [a-z]{n}, [a-z0-9]{n}, etc.
    fn generate_from_regex(pattern: &str) -> Vec<String> {
        // Parse common regex patterns
        let pattern = pattern.trim_start_matches('^').trim_end_matches('$');

        // Handle {n} quantifier patterns like [a-z]{3}
        if let Some(captures) = regex_pattern_parse(pattern) {
            let (charset, count) = captures;
            return generate_cartesian_product(&charset, count);
        }

        // Fallback: treat as literal
        vec![pattern.to_string()]
    }

    /// Generate domain prefixes from a wildcard pattern
    /// '?' matches a single character from [a-z]
    fn generate_from_wildcard(pattern: &str) -> Vec<String> {
        let question_count = pattern.chars().filter(|&c| c == '?').count();
        if question_count == 0 {
            return vec![pattern.to_string()];
        }
        // Replace ? with [a-z] and generate
        let charset: Vec<char> = ('a'..='z').collect();
        generate_cartesian_product(&charset, question_count)
    }
}

/// Parse regex patterns like [a-z]{3} or [a-z0-9]{4}
fn regex_pattern_parse(pattern: &str) -> Option<(Vec<char>, usize)> {
    // Match [charset]{count} patterns
    let re = regex_lite::Regex::new(r"^\[([^\]]+)\]\{(\d+)\}$").ok()?;
    let caps = re.captures(pattern)?;
    let charset_str = caps.get(1)?.as_str();
    let count: usize = caps.get(2)?.as_str().parse().ok()?;

    let charset = parse_charset(charset_str)?;
    if charset.is_empty() || count == 0 || count > 6 {
        return None;
    }
    Some((charset, count))
}

/// Parse charset string like "a-z", "a-z0-9", "0-9"
fn parse_charset(s: &str) -> Option<Vec<char>> {
    let mut chars = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if i + 2 < bytes.len() && bytes[i + 1] == b'-' {
            let start = bytes[i];
            let end = bytes[i + 2];
            if start <= end {
                for c in start..=end {
                    chars.push(c as char);
                }
            }
            i += 3;
        } else {
            chars.push(bytes[i] as char);
            i += 1;
        }
    }
    if chars.is_empty() { None } else { Some(chars) }
}

/// Generate cartesian product of charset repeated count times
fn generate_cartesian_product(charset: &[char], count: usize) -> Vec<String> {
    if count == 0 {
        return vec![String::new()];
    }
    let mut results = vec![String::new()];
    for _ in 0..count {
        let mut new_results = Vec::with_capacity(results.len() * charset.len());
        for prefix in &results {
            for c in charset {
                new_results.push(format!("{}{}", prefix, c));
            }
        }
        results = new_results;
    }
    results
}

/// Estimate the number of candidates a pattern will generate
pub fn estimate_pattern_count(pattern: &str) -> u64 {
    let pattern = pattern.trim_start_matches('^').trim_end_matches('$');
    if let Some((charset, count)) = regex_pattern_parse(pattern) {
        (charset.len() as u64).pow(count as u32)
    } else {
        1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_from_regex_3letter() {
        let candidates = ListGenerator::generate_from_regex("^[a-z]{3}$");
        assert_eq!(candidates.len(), 17576); // 26^3
        assert_eq!(candidates[0], "aaa");
        assert_eq!(candidates[17575], "zzz");
    }

    #[test]
    fn test_generate_from_regex_digits() {
        let candidates = ListGenerator::generate_from_regex("^[0-9]{2}$");
        assert_eq!(candidates.len(), 100); // 10^2
        assert_eq!(candidates[0], "00");
        assert_eq!(candidates[99], "99");
    }

    #[test]
    fn test_generate_from_wildcard() {
        let candidates = ListGenerator::generate_from_wildcard("??");
        assert_eq!(candidates.len(), 676); // 26^2
        assert_eq!(candidates[0], "aa");
        assert_eq!(candidates[675], "zz");
    }

    #[test]
    fn test_manual_mode() {
        let mode = ScanMode::Manual {
            domains: vec!["hello".to_string(), "world".to_string()],
        };
        let gen = ListGenerator::new(mode, ".com".to_string());
        assert_eq!(gen.total_count(), 2);
    }

    #[test]
    fn test_next_batch() {
        let mode = ScanMode::Regex { pattern: "^[a-z]{2}$".to_string() };
        let mut gen = ListGenerator::new(mode, ".com".to_string()).with_batch_size(100);
        assert_eq!(gen.total_count(), 676); // 26^2

        let batch1 = gen.next_batch();
        assert_eq!(batch1.len(), 100);
        assert_eq!(batch1[0].domain, "aa.com"); // 2-letter: first is "aa"
        assert_eq!(batch1[0].index, 0);

        let batch2 = gen.next_batch();
        assert_eq!(batch2.len(), 100);
        assert_eq!(batch2[0].index, 100);
    }

    #[test]
    fn test_has_more_and_current_index() {
        let mode = ScanMode::Manual {
            domains: vec!["test".to_string()],
        };
        let mut gen = ListGenerator::new(mode, ".com".to_string()).with_batch_size(5000);
        assert!(gen.has_more());
        assert_eq!(gen.current_index(), 0);
        gen.next_batch();
        assert!(!gen.has_more());
        assert_eq!(gen.current_index(), 1);
    }

    #[test]
    fn test_resume_from_index() {
        let mode = ScanMode::Regex { pattern: "^[a-z]{2}$".to_string() };
        let mut gen = ListGenerator::new(mode, ".com".to_string())
            .with_batch_size(100)
            .with_start_index(200);
        assert_eq!(gen.current_index(), 200);
        let batch = gen.next_batch();
        assert_eq!(batch[0].index, 200);
    }

    #[test]
    fn test_estimate_pattern_count() {
        assert_eq!(estimate_pattern_count("^[a-z]{3}$"), 17576);
        assert_eq!(estimate_pattern_count("^[a-z]{2}$"), 676);
        assert_eq!(estimate_pattern_count("^[0-9]{4}$"), 10000);
    }
}
